version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_chatbot
    networks:
      - app_network

  mcp-server:
    image: mcp-server
    container_name: mcp_server_chatbot
    ports:
      - "8050:8050"
    networks:
      - app_network

  celery_worker:
    build: .
    command: celery -A celery_app_worker worker --concurrency=5 -n worker1
    container_name: celery_worker_chatbot
    depends_on:
      - redis
      - mcp-server
    networks:
      - app_network

  fastapi_app:
    build: .
    container_name: fastapi_app_chatbot
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
      - mcp-server
    networks:
      - app_network

  flower:
    image: mher/flower
    container_name: flower_chatbot
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
